sched/core: Use task_struct::__state for sprd rotation
Since commit 498eaa3 ("sched: Change task_struct::state"), the volatile
of the previously known task_struct::state (now __state) has been removed
in favor of an "unsigned int". Switch to __state for sprd rotation and use
READ_ONCE() since we are only checking the value with the if-clause.

This fixes the following error:

../kernel/sched/core.c:5320:37: error: no member named 'state' in 'struct task_struct'
 5320 |                 if (rq->misfit_task_load && curr->state == TASK_RUNNING &&
      |                                             ~~~~  ^

[also pick raw_spin_unlock_irqrestore() -> raw_spin_rq_unlock_irqrestore()
in load_balance() by Tashar02]

Fixes: dc89dd7 ("sched: Introduce task-rotation feature")

Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>