arm64/perf: Fix mismatched parameters in sched_switch trace callback
Since [1] and [2], sched_switch trace callback has a new "prev_state"
parameter added. Due to the lack of the parameter in tracectr_notifier()
of perf_trace_counters.c, we are met with the following compilation
errors:

../arch/arm64/kernel/perf_trace_counters.c: In function 'enable_tp_pid':
../arch/arm64/kernel/perf_trace_counters.c:84:45: error: passing argument 1 of 'register_trace_sched_switch' from incompatible pointer type [-Wincompatible-pointer-types]
   84 |                 register_trace_sched_switch(tracectr_notifier, NULL);
      |                                             ^~~~~~~~~~~~~~~~~
      |                                             |
      |                                             void (*)(void *, bool,  struct task_struct *, struct task_struct *) {aka void (*)(void *, _Bool,  struct task_struct *, struct task_struct *)}
In file included from ../arch/arm64/kernel/perf_trace_counters.c:8:
../include/linux/tracepoint.h:312:38: note: expected 'void (*)(void *, bool,  struct task_struct *, struct task_struct *, unsigned int)' {aka 'void (*)(void *, _Bool,  struct task_struct *, struct task_struct *, unsigned int)'} but argument is of type 'void (*)(void *, bool,  struct task_struct *, struct task_struct *)' {aka 'void (*)(void *, _Bool,  struct task_struct *, struct task_struct *)'}
  312 |         register_trace_##name(void (*probe)(data_proto),                \
      |                               ~~~~~~~^~~~~~~~~~~~~~~~~~
../include/linux/tracepoint.h:403:9: note: in expansion of macro '__DECLARE_TRACE'
  403 |         __DECLARE_TRACE(name, PARAMS(proto), PARAMS(args),              \
      |         ^~~~~~~~~~~~~~~
../include/linux/tracepoint.h:539:9: note: in expansion of macro 'DECLARE_TRACE'
  539 |         DECLARE_TRACE(name, PARAMS(proto), PARAMS(args))
      |         ^~~~~~~~~~~~~
../include/trace/events/sched.h:224:1: note: in expansion of macro 'TRACE_EVENT'
  224 | TRACE_EVENT(sched_switch,
      | ^~~~~~~~~~~
../arch/arm64/kernel/perf_trace_counters.c:50:6: note: 'tracectr_notifier' declared here
   50 | void tracectr_notifier(void *ignore, bool preempt,
      |      ^~~~~~~~~~~~~~~~~
../arch/arm64/kernel/perf_trace_counters.c: In function 'disable_tp_pid':
../arch/arm64/kernel/perf_trace_counters.c:92:47: error: passing argument 1 of 'unregister_trace_sched_switch' from incompatible pointer type [-Wincompatible-pointer-types]
   92 |                 unregister_trace_sched_switch(tracectr_notifier, NULL);
      |                                               ^~~~~~~~~~~~~~~~~
      |                                               |
      |                                               void (*)(void *, bool,  struct task_struct *, struct task_struct *) {aka void (*)(void *, _Bool,  struct task_struct *, struct task_struct *)}
../include/linux/tracepoint.h:318:40: note: expected 'void (*)(void *, bool,  struct task_struct *, struct task_struct *, unsigned int)' {aka 'void (*)(void *, _Bool,  struct task_struct *, struct task_struct *, unsigned int)'} but argument is of type 'void (*)(void *, bool,  struct task_struct *, struct task_struct *)' {aka 'void (*)(void *, _Bool,  struct task_struct *, struct task_struct *)'}
  318 |         unregister_trace_##name(void (*probe)(data_proto),              \
      |                                 ~~~~~~~^~~~~~~~~~~~~~~~~~
../include/linux/tracepoint.h:403:9: note: in expansion of macro '__DECLARE_TRACE'
  403 |         __DECLARE_TRACE(name, PARAMS(proto), PARAMS(args),              \
      |         ^~~~~~~~~~~~~~~
../include/linux/tracepoint.h:539:9: note: in expansion of macro 'DECLARE_TRACE'
  539 |         DECLARE_TRACE(name, PARAMS(proto), PARAMS(args))
      |         ^~~~~~~~~~~~~
../include/trace/events/sched.h:224:1: note: in expansion of macro 'TRACE_EVENT'
  224 | TRACE_EVENT(sched_switch,
      | ^~~~~~~~~~~
../arch/arm64/kernel/perf_trace_counters.c:50:6: note: 'tracectr_notifier' declared here
   50 | void tracectr_notifier(void *ignore, bool preempt,
      |      ^~~~~~~~~~~~~~~~~

Add the missing prev_state parameter in tracectr_notifier() and while at it,
fix the function parameter for ARM platforms as well.

[1] 2c400c39d36b6 ("sched/tracing: Don't re-read p->state when emitting sched_switch event")
[2] 40749433c8ec5 ("sched/tracing: Append prev_state to tp args instead")

Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>