rtmutex: Fix incompatible function pointer for rt_mutex_[timed]_fastlock()
Since commit 498eaa3d039 ("sched: Change task_struct::state"), the volatile
of the previously known task_struct::state (now __state) has been removed in
favor of an "unsigned int" which was not covered in the commit for
rt_mutex_fastlock(), and therefore, it generates the following errors:

../kernel/locking/rtmutex.c:1472:48: error: incompatible function pointer types passing 'int (struct rt_mutex *, unsigned int, struct hrtimer_sleeper *, enum rtmutex_chainwalk)' to parameter of type 'int (*)(struct rt_mutex *, int, struct hrtimer_sleeper *, enum rtmutex_chainwalk)' [-Wincompatible-function-pointer-types]
 1472 |         rt_mutex_fastlock(lock, TASK_UNINTERRUPTIBLE, rt_mutex_slowlock);
      |                                                       ^~~~~~~~~~~~~~~~~
../kernel/locking/rtmutex.c:1407:11: note: passing argument to parameter 'slowfn' here
 1407 |                   int (*slowfn)(struct rt_mutex *lock, int state,
      |                         ^

../kernel/locking/rtmutex.c:1562:12: error: incompatible function pointer types passing 'int (struct rt_mutex *, unsigned int, struct hrtimer_sleeper *, enum rtmutex_chainwalk)' to parameter of type 'int (*)(struct rt_mutex *, int, struct hrtimer_sleeper *, enum rtmutex_chainwalk)' [-Wincompatible-function-pointer-types]
 1562 |                                        rt_mutex_slowlock);
      |                                        ^~~~~~~~~~~~~~~~~
../kernel/locking/rtmutex.c:1421:10: note: passing argument to parameter 'slowfn' here
 1421 |                         int (*slowfn)(struct rt_mutex *lock, int state,
      |                               ^

Change the "state" type from int to unsigned int to fix it.

Fixes: 498eaa3d039 ("sched: Change task_struct::state")
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>